### ISSUE TITLE
Introduce Github Enterprise 

### ISSUE THREAD

**Issue by stevieschatz** [cardinalby/schedule-job-action#7]
Hello @cardinalby, this action seems like a great little GitHub action and when I found it I was so excited because for our use case it fits perfectly however, there appears to be a problem using it with GitHub Enterprise since it makes the calls to the public GitHub API.

It would be much appreciated if you could make this configurable. See here [octokit-enterprise](https://github.com/octokit/plugin-enterprise-server.js/)

For example by passing into the action the enterprise host `baseUrl: "https://github.acme-inc.com/api/v3"`.

Let me know what you think.

**Comment by cardinalby** [comment]
Hi! Thanks for the feedback :)

I'm actually have never dealt with GitHub Enterprise and don't know about differences in API it has comparing to public GitHub API. If these basics endpoints the action utilises are the same, probably it should work by passing a different API url.

I have created the `custom_api_url` branch which you can reference in your workflow as `cardinalby/schedule-job-action@custom_api_url` and `cardinalby/unschedule-job-action@custom_api_url` correspondingly. In this branch I pass `GITHUB_API_URL` env variable to octokit options as a `baseUrl`. Normally, this env variable is set by GitHub to `https://api.github.com`. I expect that on GitHub Enterprise installation it should have custom value (try to specify it explicitly in job/step if it doesn't). 

Please test this branch and let me know if it works. Otherwise, it would require more changes:

Octokit library version used in these actions is a bit outdated, I avoided updating it because they have complicated TypeScript typing system and even after minor updates of it (or TS compiler version) code gets broken (I don't know how they managed to make simple API wrapper so complicated :) )

Also, take a look at my [blog post](https://cardinalby.github.io/blog/post/github-actions/implementing-deferred-steps/) about scheduled actions. Actually, I migrated to the "Dispatched workflow calling itself" approach in my workflows, it seems more natural and doesn't bloat a commit history.

**Comment by stevieschatz** [comment]
Thank you so much for the fast feedback here I will def test this out and provide feedback here over the weekend!

**Comment by stevieschatz** [comment]
I can confirm this update resolved our issue. Thank you again!

**Comment by cardinalby** [comment]
Was it necessary to pass API url to `GITHUB_API_URL` manually or it just works?

**Comment by stevieschatz** [comment]
Just worked ! No manually passing.

**Comment by cardinalby** [comment]
Thanks for the clarification. I merged this change and now it's available under:

`cardinalby/schedule-job-action@v1`,
`cardinalby/schedule-job-action@master`,
`cardinalby/schedule-job-action@1.0.3`,

`cardinalby/unschedule-job-action@v1`,
`cardinalby/unschedule-job-action@master`,
`cardinalby/unschedule-job-action@1.0.4`

Please update your workflow, I will delete the temporary `custom_api_url` branch in a week
